services:
  web:
    image: php:8.4-apache
    restart: always
    build: .
    container_name: ${APP_NAME}-apache
    volumes:
      - ./${APACHE_HTDOCS}:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${APACHE_PORT}:80"
    networks:
      - develop-network
    depends_on:
      - db
      - redis
    environment:
      WORDPRESS_DB_HOST: db:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_APP_NAME: ${APP_NAME}
      WORDPRESS_REDIS_PORT: ${REDIS_PORT}

  db:
    image: mariadb:${MARIADB_VERSION}
    restart: always
    container_name: ${APP_NAME}-mariadb
    environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MARIADB_LOCAL_DIR}${MARIADB_DATA_DIR}:/var/lib/mysql
      - ${MARIADB_LOCAL_DIR}${MARIADB_CONF_DIR}:/etc/mysql/conf.d
      - ${MARIADB_LOCAL_DIR}${MARIADB_ETC_DIR}:/etc/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - develop-network

  redis:
    image: redis:7
    restart: always
    container_name: ${APP_NAME}-redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - develop-network

networks:
  develop-network:
    driver: bridge

volumes:
  db_data:
