version: '3.8'

services:
  web:
    image: php:8.3-apache
    build: .
    container_name: php-apache
    volumes:
      - ./${APACHE_HTDOCS}:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${APACHE_PORT}:80"
    networks:
      - tdm-network
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MARIADB_LOCAL_DIR}${MARIADB_DATA_DIR}:/var/lib/mysql
      - ${MARIADB_LOCAL_DIR}${MARIADB_CONF_DIR}:/etc/mysql/conf.d
      - ${MARIADB_LOCAL_DIR}${MARIADB_ETC_DIR}:/etc/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - tdm-network

networks:
  tdm-network:
    driver: bridge

volumes:
  db_data:
